[package]
name = "glass-a11y-linux"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[target.'cfg(target_os = "linux")'.dependencies]
glass-core.workspace = true
glass-dbus-linux.workspace = true
glass-exec-unix.workspace = true
atspi.workspace = true
atspi-common.workspace = true
zbus.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dev-dependencies]
glass-proc-linux.workspace = true
glass-x11 = { path = "../glass-x11" }
glass-wayland = { path = "../glass-wayland" }
tempfile.workspace = true

[lints]
workspace = true
